### ISSUE TITLE
Error Message when loading footprints

### ISSUE THREAD

**Issue by spacemishka** [aeberbach/A1200KB#3]
Hello,

i got this error message when i tried "Assign Footprints"

```
Errors were encountered loading footprints:
Footprint library path "/Users/adam/Projects/MX_Alps_Hybrid.pretty" does not exist
```
Can you may add this library?

thanks!

**Comment by aeberbach** [comment]
I have a clean PC install here and after installing KiCAD and syncing only this project I saw the same error. The library it is trying to load can be found at https://github.com/ai03-2725/MX_Alps_Hybrid. I highly recommend cloning a local copy and adding it to your KiCAD library. I prefer not to add a local copy to this repo as it works without and you may be better off making it useful as your own library for all projects not just this one.
