### ISSUE TITLE
Error in soldering mask

### ISSUE THREAD

**Issue by OleUrgast** [aeberbach/A1200KB#6]
Hello,
ordering the A1200kb PCB from pcbway yesterday they hinted an error in soldering mask:

"  About your order ,as the attache dpic showed, the pointed solderask openings at top side will expose the traces, pls advise if you can accept that and produce as your file?
Looking forward to your reply."
![W388748ASV44-EQ](https://user-images.githubusercontent.com/33391764/152323849-4194c72c-ad9f-47bd-a87f-9d2aace8072c.png)

Of course this is not a big issue, so I confimed to produce the PCB as uploaded. But you might correct the solder mask in future revisions.

**Comment by skielek** [comment]
Yea those are mistakes on the space and return keys, you dont want to expose the copper there or anywhere on the front. In fact, the switch footprints already have the necessary stencil mask, so there's no need that I see for any additional customisation of openings in the soldermask (front or back).

**Comment by aeberbach** [comment]
This is an issue with the key library. Not ideal but functionally does not matter.
