### ISSUE TITLE
Cherry MX compatible keycaps

### ISSUE THREAD

**Issue by gotnull** [aeberbach/A1200KB#7]
Is there anywhere to get Amiga-specific Cherry MX compatible keycaps?

**Comment by aeberbach** [comment]
Many, many places. I have bought recently from Keychron in Australia but you can also try Amazon, Akko, just search.

**Comment by gotnull** [comment]
> Many, many places. I have bought recently from Keychron in Australia but you can also try Amazon, Akko, just search.

I meant Amiga-specific Cherry MX keycaps.

**Comment by aeberbach** [comment]
I did just see user steveed on amibay advertising some - I think he had sets made at Signature Plastics. They are not cheap but they look very good, by far your best option. It is much more expensive piecing together a set with custom keys.
